[27/Oct/2020 09:12:09] "GET /WES/index/ HTTP/1.1" 200 11014
Not Found: /favicon.ico
[27/Oct/2020 09:12:09] "GET /favicon.ico HTTP/1.1" 404 3507
[27/Oct/2020 09:12:43] "GET /Sanger/index/ HTTP/1.1" 200 10224
Not Found: /favicon.ico
[27/Oct/2020 09:12:43] "GET /favicon.ico HTTP/1.1" 404 3507
[27/Oct/2020 09:12:57] "GET /patiantinfo/ HTTP/1.1" 200 10391
Not Found: /favicon.ico
[27/Oct/2020 09:12:58] "GET /favicon.ico HTTP/1.1" 404 3507
[27/Oct/2020 09:13:13] "GET /Sanger/index/ HTTP/1.1" 200 10224
Not Found: /favicon.ico
[27/Oct/2020 09:13:14] "GET /favicon.ico HTTP/1.1" 404 3507
[27/Oct/2020 09:13:15] "GET /Sanger/index/ HTTP/1.1" 200 10224
[27/Oct/2020 09:13:16] "GET /Sanger/new/ HTTP/1.1" 200 7782
Not Found: /favicon.ico
[27/Oct/2020 09:13:16] "GET /favicon.ico HTTP/1.1" 404 3507
cp: cannot stat ‘/mnt/dfc_data1/home/lixuefei/chromat_di’: No such file or directory
[27/Oct/2020 09:14:20] "POST /Sanger/new/ HTTP/1.1" 200 6446
readline() on closed filehandle IN at /mnt/dfc_data1/home/zhangyongjun/database/gtc/ODS/convert2annovar.pl line 31.
[27/Oct/2020 09:14:23] "GET /Sanger/index/ HTTP/1.1" 200 10459
Not Found: /favicon.ico
[27/Oct/2020 09:14:23] "GET /favicon.ico HTTP/1.1" 404 3507
No such file or directory at /mnt/dfc_data1/home/zhangyongjun/database/gtc/ODS/SNPHTML.pl line 32.
No such file or directory at /mnt/dfc_data1/home/zhangyongjun/database/gtc/ODS/Exoncover.pl line 14.
[27/Oct/2020 09:14:57] "GET /Sanger/index/ HTTP/1.1" 200 10459
No such file or directory at /mnt/dfc_data1/home/zhangyongjun/database/gtc/ODS/SNPimg2html.pl line 17.
No such file or directory at /mnt/dfc_data1/home/zhangyongjun/database/gtc/ODS/create_html_report.pl line 25.
[27/Oct/2020 09:15:00] "GET /WES/index/ HTTP/1.1" 200 11014
Not Found: /favicon.ico
[27/Oct/2020 09:15:00] "GET /favicon.ico HTTP/1.1" 404 3507
[27/Oct/2020 09:15:05] "GET /Sanger/index/ HTTP/1.1" 200 10519
Not Found: /favicon.ico
[27/Oct/2020 09:15:05] "GET /favicon.ico HTTP/1.1" 404 3507
[27/Oct/2020 09:15:08] "GET /Sanger/new/ HTTP/1.1" 200 7782
Not Found: /favicon.ico
[27/Oct/2020 09:15:08] "GET /favicon.ico HTTP/1.1" 404 3507
[27/Oct/2020 09:15:55] "POST /Sanger/new/ HTTP/1.1" 200 6446
[27/Oct/2020 09:15:58] "GET /patiantinfo/ HTTP/1.1" 200 10391
Not Found: /favicon.ico
[27/Oct/2020 09:15:59] "GET /favicon.ico HTTP/1.1" 404 3507
[27/Oct/2020 09:15:59] "GET /WES/index/ HTTP/1.1" 200 11014
Not Found: /favicon.ico
[27/Oct/2020 09:15:59] "GET /favicon.ico HTTP/1.1" 404 3507
[27/Oct/2020 09:16:03] "GET /Sanger/index/ HTTP/1.1" 200 10756
Not Found: /favicon.ico
[27/Oct/2020 09:16:03] "GET /favicon.ico HTTP/1.1" 404 3507
[27/Oct/2020 09:16:18] "GET /patiantinfo/ HTTP/1.1" 200 10391
Not Found: /favicon.ico
[27/Oct/2020 09:16:18] "GET /favicon.ico HTTP/1.1" 404 3507
[27/Oct/2020 09:16:19] "GET /Sanger/index/ HTTP/1.1" 200 10756
Not Found: /favicon.ico
[27/Oct/2020 09:16:20] "GET /favicon.ico HTTP/1.1" 404 3507
[27/Oct/2020 09:16:21] "GET /WES/index/ HTTP/1.1" 200 11014
Not Found: /favicon.ico
[27/Oct/2020 09:16:21] "GET /favicon.ico HTTP/1.1" 404 3507
[27/Oct/2020 09:16:24] "GET /Sanger/index/ HTTP/1.1" 200 10756
Not Found: /favicon.ico
[27/Oct/2020 09:16:24] "GET /favicon.ico HTTP/1.1" 404 3507
[27/Oct/2020 09:16:26] "GET /WES/index/ HTTP/1.1" 200 11014
Not Found: /favicon.ico
[27/Oct/2020 09:16:26] "GET /favicon.ico HTTP/1.1" 404 3507
[27/Oct/2020 09:18:03] "GET /WES/index/ HTTP/1.1" 200 10992
Not Found: /favicon.ico
[27/Oct/2020 09:24:41] "GET /favicon.ico HTTP/1.1" 404 3507
[27/Oct/2020 09:24:44] "GET /Sanger/index/ HTTP/1.1" 200 10818
Not Found: /favicon.ico
[27/Oct/2020 09:24:45] "GET /favicon.ico HTTP/1.1" 404 3507
[27/Oct/2020 09:24:47] "GET /WES/index/ HTTP/1.1" 200 11014
Not Found: /favicon.ico
[27/Oct/2020 09:24:48] "GET /favicon.ico HTTP/1.1" 404 3507
[27/Oct/2020 09:24:51] "GET /Sanger/index/ HTTP/1.1" 200 10818
Not Found: /favicon.ico
[27/Oct/2020 09:24:51] "GET /favicon.ico HTTP/1.1" 404 3507
[27/Oct/2020 09:25:06] "GET /Sanger//mnt/dfc_data1/project/lixuefei/Sanger/NGSWES1-1-1/ALL.html HTTP/1.1" 200 5245323
[27/Oct/2020 09:33:47] "GET /WES/index/ HTTP/1.1" 200 11014
Not Found: /favicon.ico
[27/Oct/2020 09:33:48] "GET /favicon.ico HTTP/1.1" 404 3507
Not Found: /favicon.ico
[27/Oct/2020 09:35:18] "GET /favicon.ico HTTP/1.1" 404 3507
Not Found: /favicon.ico
[27/Oct/2020 09:35:18] "GET /favicon.ico HTTP/1.1" 404 3507
Not Found: /favicon.ico
[27/Oct/2020 09:35:19] "GET /favicon.ico HTTP/1.1" 404 3507
Not Found: /favicon.ico
[27/Oct/2020 09:35:19] "GET /favicon.ico HTTP/1.1" 404 3507
----------------------------------------
Exception happened during processing of request from ('172.16.100.115', 58559)
Traceback (most recent call last):
  File "/mnt/dfc_data1/software/anaconda3/lib/python3.7/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/mnt/dfc_data1/software/anaconda3/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/mnt/dfc_data1/software/anaconda3/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/mnt/dfc_data1/software/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
  File "/mnt/dfc_data1/software/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/mnt/dfc_data1/software/anaconda3/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
Not Found: /favicon.ico
[27/Oct/2020 09:35:44] "GET /favicon.ico HTTP/1.1" 404 3507
Not Found: /favicon.ico
[27/Oct/2020 09:35:44] "GET /favicon.ico HTTP/1.1" 404 3507
Not Found: /favicon.ico
[27/Oct/2020 09:35:45] "GET /favicon.ico HTTP/1.1" 404 3507
Not Found: /favicon.ico
[27/Oct/2020 09:35:45] "GET /favicon.ico HTTP/1.1" 404 3507
Not Found: /favicon.ico
[27/Oct/2020 09:35:46] "GET /favicon.ico HTTP/1.1" 404 3507
Not Found: /favicon.ico
[27/Oct/2020 09:35:47] "GET /favicon.ico HTTP/1.1" 404 3507
Not Found: /favicon.ico
[27/Oct/2020 09:35:47] "GET /favicon.ico HTTP/1.1" 404 3507
Not Found: /favicon.ico
[27/Oct/2020 09:47:12] "GET /favicon.ico HTTP/1.1" 404 3507
Not Found: /favicon.ico
[27/Oct/2020 09:47:13] "GET /favicon.ico HTTP/1.1" 404 3507
[28/Oct/2020 08:00:20] "GET / HTTP/1.1" 200 6227
[28/Oct/2020 08:00:20] "GET /static/plugins/jquery/jquery.min.js HTTP/1.1" 200 88145
[28/Oct/2020 08:00:20] "GET /static/dist/img/AdminLTELogo.png HTTP/1.1" 200 10380
[28/Oct/2020 08:00:20] "GET /static/dist/js/adminlte.min.js HTTP/1.1" 200 25193
[28/Oct/2020 08:00:20] "GET /static/dist/img/user2-160x160.jpg HTTP/1.1" 200 7070
[28/Oct/2020 08:00:20] "GET /static/plugins/bootstrap/js/bootstrap.bundle.min.js HTTP/1.1" 200 80698
[28/Oct/2020 08:00:20] "GET /static/plugins/fontawesome-free/css/all.min.css HTTP/1.1" 200 58578
[28/Oct/2020 08:00:20] "GET /static/dist/css/adminlte.min.css HTTP/1.1" 200 689320
[28/Oct/2020 08:00:20] "GET /static/plugins/fontawesome-free/webfonts/fa-regular-400.woff2 HTTP/1.1" 200 13584
[28/Oct/2020 08:00:20] "GET /static/plugins/fontawesome-free/webfonts/fa-solid-900.woff2 HTTP/1.1" 200 79444
Not Found: /favicon.ico
[28/Oct/2020 08:00:21] "GET /favicon.ico HTTP/1.1" 404 3507
[30/Oct/2020 08:23:51] "GET / HTTP/1.1" 200 6227
Not Found: /favicon.ico
[30/Oct/2020 08:23:51] "GET /favicon.ico HTTP/1.1" 404 3507
[30/Oct/2020 08:23:54] "GET /login/ HTTP/1.1" 200 7645
[30/Oct/2020 08:23:56] "GET /captchaimage/3c9aa67ff06a36e33a07c9bf92047874e4ab337d/ HTTP/1.1" 200 4703
[30/Oct/2020 08:24:04] "POST /login/ HTTP/1.1" 302 0
[30/Oct/2020 08:24:04] "GET /index/ HTTP/1.1" 200 6441
[30/Oct/2020 08:24:07] "GET /WES/index/ HTTP/1.1" 200 11468
[30/Oct/2020 08:24:17] "GET /WES/NGSWES1/ HTTP/1.1" 200 9519
[30/Oct/2020 08:24:20] "GET /WES//mnt/dfc_data1/project/lixuefei/WES/NGSWES1/Run/6.Final/AllIntergrateMutation.xlsx HTTP/1.1" 200 37133593
[30/Oct/2020 08:24:20] "GET /WES/index/ HTTP/1.1" 200 11468
[30/Oct/2020 08:24:21] "GET /Sanger/index/ HTTP/1.1" 200 10796
[30/Oct/2020 08:24:28] "GET /Sanger//mnt/dfc_data1/project/lixuefei/Sanger/NGSWES1-1-1/ALL.html HTTP/1.1" 200 5245323
[30/Oct/2020 08:25:00] "GET /Report/ HTTP/1.1" 200 10857
[30/Oct/2020 08:25:02] "GET /Report/FPR0003/ HTTP/1.1" 200 14578
Not Found: /favicon.ico
[02/Nov/2020 12:23:55] "GET /favicon.ico HTTP/1.1" 404 3507
Not Found: /favicon.ico
[02/Nov/2020 12:23:55] "GET /favicon.ico HTTP/1.1" 404 3507
Not Found: /favicon.ico
[02/Nov/2020 12:24:06] "GET /favicon.ico HTTP/1.1" 404 3507
Not Found: /favicon.ico
[02/Nov/2020 12:24:06] "GET /favicon.ico HTTP/1.1" 404 3507
Not Found: /favicon.ico
[02/Nov/2020 12:24:09] "GET /favicon.ico HTTP/1.1" 404 3507
Not Found: /favicon.ico
[02/Nov/2020 12:24:10] "GET /favicon.ico HTTP/1.1" 404 3507
Not Found: /favicon.ico
[02/Nov/2020 12:24:11] "GET /favicon.ico HTTP/1.1" 404 3507
Not Found: /favicon.ico
[02/Nov/2020 12:24:11] "GET /favicon.ico HTTP/1.1" 404 3507
Not Found: /favicon.ico
[02/Nov/2020 12:24:12] "GET /favicon.ico HTTP/1.1" 404 3507
Not Found: /favicon.ico
[02/Nov/2020 12:24:12] "GET /favicon.ico HTTP/1.1" 404 3507
Not Found: /favicon.ico
[02/Nov/2020 12:24:13] "GET /favicon.ico HTTP/1.1" 404 3507
Not Found: /favicon.ico
[02/Nov/2020 12:24:14] "GET /favicon.ico HTTP/1.1" 404 3507
Not Found: /favicon.ico
[02/Nov/2020 12:24:14] "GET /favicon.ico HTTP/1.1" 404 3507
Not Found: /favicon.ico
[02/Nov/2020 12:24:15] "GET /favicon.ico HTTP/1.1" 404 3507
[02/Nov/2020 12:24:16] "GET / HTTP/1.1" 200 6227
[02/Nov/2020 12:24:16] "GET /static/dist/img/user2-160x160.jpg HTTP/1.1" 200 7070
[02/Nov/2020 12:24:16] "GET /static/plugins/fontawesome-free/css/all.min.css HTTP/1.1" 200 58578
[02/Nov/2020 12:24:16] "GET /static/dist/js/adminlte.min.js HTTP/1.1" 200 25193
[02/Nov/2020 12:24:16] "GET /static/dist/img/AdminLTELogo.png HTTP/1.1" 200 10380
[02/Nov/2020 12:24:16] "GET /static/plugins/jquery/jquery.min.js HTTP/1.1" 200 88145
[02/Nov/2020 12:24:16] "GET /static/plugins/bootstrap/js/bootstrap.bundle.min.js HTTP/1.1" 200 80698
[02/Nov/2020 12:24:16] "GET /static/dist/css/adminlte.min.css HTTP/1.1" 200 689320
[02/Nov/2020 12:24:16] "GET /static/plugins/fontawesome-free/webfonts/fa-regular-400.eot? HTTP/1.1" 200 34390
[02/Nov/2020 12:24:16] "GET /static/plugins/fontawesome-free/webfonts/fa-solid-900.eot? HTTP/1.1" 200 202902
Not Found: /favicon.ico
[02/Nov/2020 12:24:17] "GET /favicon.ico HTTP/1.1" 404 3507
[02/Nov/2020 12:24:19] "GET /Sanger/index/ HTTP/1.1" 200 6154
Not Found: /favicon.ico
[02/Nov/2020 12:24:19] "GET /favicon.ico HTTP/1.1" 404 3507
[02/Nov/2020 12:24:19] "GET /WES/index/ HTTP/1.1" 200 6154
Not Found: /favicon.ico
[02/Nov/2020 12:24:20] "GET /favicon.ico HTTP/1.1" 404 3507
[02/Nov/2020 12:24:21] "GET /login/ HTTP/1.1" 200 7645
[02/Nov/2020 12:24:22] "GET /static/dist/css/login.css HTTP/1.1" 200 634
[02/Nov/2020 12:24:22] "GET /captchaimage/cbbb81ba3c2d804d98b3a70791468442b1310c0a/ HTTP/1.1" 200 4439
Not Found: /favicon.ico
[02/Nov/2020 12:24:22] "GET /favicon.ico HTTP/1.1" 404 3507
[02/Nov/2020 12:24:48] "POST /login/ HTTP/1.1" 302 0
[02/Nov/2020 12:24:48] "GET /index/ HTTP/1.1" 200 6463
Not Found: /favicon.ico
[02/Nov/2020 12:24:48] "GET /favicon.ico HTTP/1.1" 404 3507
[02/Nov/2020 12:24:51] "GET /WES/index/ HTTP/1.1" 200 11490
[02/Nov/2020 12:24:51] "GET /static/plugins/DataTables/Buttons-1.6.2/js/buttons.html5.min.js HTTP/1.1" 200 25035
[02/Nov/2020 12:24:51] "GET /static/plugins/DataTables/Buttons-1.6.2/css/buttons.dataTables.min.css HTTP/1.1" 200 9773
[02/Nov/2020 12:24:51] "GET /static/plugins/DataTables/Buttons-1.6.2/js/buttons.flash.min.js HTTP/1.1" 200 26231
[02/Nov/2020 12:24:51] "GET /static/plugins/DataTables/Buttons-1.6.2/js/dataTables.buttons.min.js HTTP/1.1" 200 19816
[02/Nov/2020 12:24:51] "GET /static/plugins/DataTables/DataTables-1.10.21/css/jquery.dataTables.min.css HTTP/1.1" 200 13892
[02/Nov/2020 12:24:51] "GET /static/plugins/DataTables/Buttons-1.6.2/js/buttons.print.min.js HTTP/1.1" 200 2302
[02/Nov/2020 12:24:51] "GET /static/plugins/DataTables/JSZip-2.5.0/jszip.min.js HTTP/1.1" 200 76985
[02/Nov/2020 12:24:51] "GET /static/plugins/DataTables/DataTables-1.10.21/js/jquery.dataTables.min.js HTTP/1.1" 200 84647
[02/Nov/2020 12:24:51] "GET /static/plugins/DataTables/pdfmake-0.1.36/vfs_fonts.js HTTP/1.1" 200 870284
[02/Nov/2020 12:24:51] "GET /static/plugins/DataTables/pdfmake-0.1.36/pdfmake.min.js HTTP/1.1" 200 970387
Not Found: /favicon.ico
[02/Nov/2020 12:24:51] "GET /favicon.ico HTTP/1.1" 404 3507
[02/Nov/2020 12:24:52] "GET /Sanger/index/ HTTP/1.1" 200 10818
[02/Nov/2020 12:24:52] "GET /static/plugins/DataTables/DataTables-1.10.21/images/sort_both.png HTTP/1.1" 200 201
[02/Nov/2020 12:24:52] "GET /static/plugins/DataTables/DataTables-1.10.21/images/sort_asc.png HTTP/1.1" 200 160
Not Found: /favicon.ico
[02/Nov/2020 12:24:52] "GET /favicon.ico HTTP/1.1" 404 3507
[02/Nov/2020 12:24:54] "GET /WES/index/ HTTP/1.1" 200 11490
Not Found: /favicon.ico
[02/Nov/2020 12:24:54] "GET /favicon.ico HTTP/1.1" 404 3507
[02/Nov/2020 12:24:55] "GET /Sanger/index/ HTTP/1.1" 200 10818
Not Found: /favicon.ico
[02/Nov/2020 12:24:56] "GET /favicon.ico HTTP/1.1" 404 3507
[02/Nov/2020 12:24:57] "GET /WES/index/ HTTP/1.1" 200 11490
Not Found: /favicon.ico
[02/Nov/2020 12:24:57] "GET /favicon.ico HTTP/1.1" 404 3507
[02/Nov/2020 12:25:02] "GET /Sanger/index/ HTTP/1.1" 200 10818
Not Found: /favicon.ico
[02/Nov/2020 12:25:02] "GET /favicon.ico HTTP/1.1" 404 3507
[02/Nov/2020 12:25:05] "GET /Sanger//mnt/dfc_data1/project/lixuefei/Sanger/NGSWES1-1/ALL.html HTTP/1.1" 200 641
[02/Nov/2020 12:25:14] "GET /Sanger/index/ HTTP/1.1" 200 10818
[02/Nov/2020 12:25:16] "GET /Sanger//mnt/dfc_data1/project/lixuefei/Sanger/NGSWES1-1/ALL.html HTTP/1.1" 200 641
[02/Nov/2020 12:25:36] "GET /Sanger//mnt/dfc_data1/project/lixuefei/Sanger/NGSWES1-1/ALL.html HTTP/1.1" 200 641
[02/Nov/2020 12:26:07] "GET /Sanger//mnt/dfc_data1/project/lixuefei/Sanger/NGSWES1-1-1/ALL.html HTTP/1.1" 200 5245323
[02/Nov/2020 12:26:28] "GET /patiantinfo/ HTTP/1.1" 200 10391
Not Found: /favicon.ico
[02/Nov/2020 12:26:29] "GET /favicon.ico HTTP/1.1" 404 3507
[02/Nov/2020 12:26:29] "GET /Sanger/index/ HTTP/1.1" 200 10818
[02/Nov/2020 12:26:30] "GET /WES/index/ HTTP/1.1" 200 11490
Not Found: /favicon.ico
[02/Nov/2020 12:26:30] "GET /favicon.ico HTTP/1.1" 404 3507
Not Found: /favicon.ico
[02/Nov/2020 12:26:30] "GET /favicon.ico HTTP/1.1" 404 3507
[02/Nov/2020 12:26:31] "GET /Sanger/index/ HTTP/1.1" 200 10818
Not Found: /favicon.ico
[02/Nov/2020 12:26:32] "GET /favicon.ico HTTP/1.1" 404 3507
[02/Nov/2020 12:26:33] "GET /WES/index/ HTTP/1.1" 200 11490
Not Found: /favicon.ico
[02/Nov/2020 12:26:33] "GET /favicon.ico HTTP/1.1" 404 3507
[02/Nov/2020 12:26:35] "GET /Report/ HTTP/1.1" 200 10879
Not Found: /favicon.ico
[02/Nov/2020 12:26:35] "GET /favicon.ico HTTP/1.1" 404 3507
[02/Nov/2020 12:26:40] "GET /Report/ HTTP/1.1" 200 10879
[02/Nov/2020 12:26:43] "GET /WES/index/ HTTP/1.1" 200 11490
Not Found: /favicon.ico
[02/Nov/2020 12:26:43] "GET /favicon.ico HTTP/1.1" 404 3507
[02/Nov/2020 12:26:44] "GET /Project/ HTTP/1.1" 200 6393
Not Found: /favicon.ico
[02/Nov/2020 12:26:44] "GET /favicon.ico HTTP/1.1" 404 3507
[02/Nov/2020 12:26:45] "GET /Report/ HTTP/1.1" 200 10879
Not Found: /favicon.ico
[02/Nov/2020 12:26:45] "GET /favicon.ico HTTP/1.1" 404 3507
[02/Nov/2020 12:26:49] "GET /Project/ HTTP/1.1" 200 6393
Not Found: /favicon.ico
[02/Nov/2020 12:26:49] "GET /favicon.ico HTTP/1.1" 404 3507
[02/Nov/2020 12:26:50] "GET /WES/index/ HTTP/1.1" 200 11490
Not Found: /favicon.ico
[02/Nov/2020 12:26:50] "GET /favicon.ico HTTP/1.1" 404 3507
Internal Server Error: /WES//mnt/dfc_data1/project/lixuefei/WES/NGSWES1/Run/6.Final/QCStat.xls
Traceback (most recent call last):
  File "/mnt/dfc_data1/software/anaconda3/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/mnt/dfc_data1/software/anaconda3/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/mnt/dfc_data1/software/anaconda3/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/mnt/dfc_data1/home/lixuefei/Pipeline/Django/GeneticDisease/WES/views.py", line 177, in DownloadFile
    files = open(file_path, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/dfc_data1/project/lixuefei/WES/NGSWES1/Run/6.Final/QCStat.xls'
[02/Nov/2020 12:26:55] "GET /WES//mnt/dfc_data1/project/lixuefei/WES/NGSWES1/Run/6.Final/QCStat.xls HTTP/1.1" 500 69801
Not Found: /favicon.ico
[02/Nov/2020 12:26:55] "GET /favicon.ico HTTP/1.1" 404 3507
[02/Nov/2020 12:26:59] "GET /Project/ HTTP/1.1" 200 6393
Not Found: /favicon.ico
[02/Nov/2020 12:26:59] "GET /favicon.ico HTTP/1.1" 404 3507
[02/Nov/2020 12:27:00] "GET /WES/index/ HTTP/1.1" 200 11490
Not Found: /favicon.ico
[02/Nov/2020 12:27:00] "GET /favicon.ico HTTP/1.1" 404 3507
[02/Nov/2020 12:27:19] "GET /WES//mnt/dfc_data1/project/lixuefei/WES/NGSWES1/Run/6.Final/AllIntergrateMutation.xlsx HTTP/1.1" 200 37133593
[02/Nov/2020 12:27:37] "GET /WES//mnt/dfc_data1/project/lixuefei/WES/NGSWES1/Run/6.Final/FinalIntergrateMutation.xlsx HTTP/1.1" 200 2380236
Not Found: /favicon.ico
[02/Nov/2020 12:31:24] "GET /favicon.ico HTTP/1.1" 404 3507
Not Found: /favicon.ico
[02/Nov/2020 12:31:25] "GET /favicon.ico HTTP/1.1" 404 3507
Not Found: /favicon.ico
[02/Nov/2020 12:31:26] "GET /favicon.ico HTTP/1.1" 404 3507
[05/Nov/2020 08:55:40] "GET / HTTP/1.1" 200 6441
[05/Nov/2020 08:55:40] "GET /static/dist/css/adminlte.min.css HTTP/1.1" 304 0
[05/Nov/2020 08:55:40] "GET /static/dist/img/user2-160x160.jpg HTTP/1.1" 304 0
[05/Nov/2020 08:55:40] "GET /static/dist/img/AdminLTELogo.png HTTP/1.1" 304 0
[05/Nov/2020 08:55:40] "GET /static/plugins/fontawesome-free/css/all.min.css HTTP/1.1" 304 0
[05/Nov/2020 08:55:40] "GET /static/plugins/bootstrap/js/bootstrap.bundle.min.js HTTP/1.1" 304 0
[05/Nov/2020 08:55:40] "GET /static/plugins/jquery/jquery.min.js HTTP/1.1" 304 0
[05/Nov/2020 08:55:40] "GET /static/dist/js/adminlte.min.js HTTP/1.1" 304 0
[05/Nov/2020 08:55:41] "GET /static/plugins/fontawesome-free/webfonts/fa-solid-900.woff2 HTTP/1.1" 304 0
[05/Nov/2020 08:55:41] "GET /static/plugins/fontawesome-free/webfonts/fa-regular-400.woff2 HTTP/1.1" 304 0
Not Found: /favicon.ico
[05/Nov/2020 08:55:41] "GET /favicon.ico HTTP/1.1" 404 3507
[05/Nov/2020 08:55:45] "GET /WES/index/ HTTP/1.1" 200 11468
[05/Nov/2020 08:55:46] "GET /static/plugins/DataTables/DataTables-1.10.21/css/jquery.dataTables.min.css HTTP/1.1" 304 0
[05/Nov/2020 08:55:46] "GET /static/plugins/DataTables/DataTables-1.10.21/js/jquery.dataTables.min.js HTTP/1.1" 304 0
[05/Nov/2020 08:55:46] "GET /static/plugins/DataTables/Buttons-1.6.2/js/buttons.html5.min.js HTTP/1.1" 304 0
[05/Nov/2020 08:55:46] "GET /static/plugins/DataTables/Buttons-1.6.2/js/buttons.flash.min.js HTTP/1.1" 304 0
[05/Nov/2020 08:55:46] "GET /static/plugins/DataTables/Buttons-1.6.2/js/dataTables.buttons.min.js HTTP/1.1" 304 0
[05/Nov/2020 08:55:46] "GET /static/plugins/DataTables/Buttons-1.6.2/css/buttons.dataTables.min.css HTTP/1.1" 304 0
[05/Nov/2020 08:55:46] "GET /static/plugins/DataTables/Buttons-1.6.2/js/buttons.print.min.js HTTP/1.1" 304 0
[05/Nov/2020 08:55:46] "GET /static/plugins/DataTables/DataTables-1.10.21/images/sort_both.png HTTP/1.1" 304 0
[05/Nov/2020 08:55:46] "GET /static/plugins/DataTables/DataTables-1.10.21/images/sort_asc.png HTTP/1.1" 304 0
Internal Server Error: /WES//mnt/dfc_data1/project/lixuefei/WES/NGSWES1/Run/6.Final/QCStat.xls
Traceback (most recent call last):
  File "/mnt/dfc_data1/software/anaconda3/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/mnt/dfc_data1/software/anaconda3/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/mnt/dfc_data1/software/anaconda3/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/mnt/dfc_data1/home/lixuefei/Pipeline/Django/GeneticDisease/WES/views.py", line 177, in DownloadFile
    files = open(file_path, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/dfc_data1/project/lixuefei/WES/NGSWES1/Run/6.Final/QCStat.xls'
[05/Nov/2020 08:55:48] "GET /WES//mnt/dfc_data1/project/lixuefei/WES/NGSWES1/Run/6.Final/QCStat.xls HTTP/1.1" 500 70688
[05/Nov/2020 08:55:55] "GET /WES/NGSWES0010001/ HTTP/1.1" 200 9555
[05/Nov/2020 08:55:57] "GET /WES//mnt/dfc_data1/project/lixuefei/WES/NGSWES1/Run/6.Final/AllIntergrateMutation.xlsx HTTP/1.1" 200 37133593
[05/Nov/2020 08:55:59] "GET /Report/ HTTP/1.1" 200 10857
[05/Nov/2020 08:56:01] "GET /Report/FPR0003/ HTTP/1.1" 200 14578
[05/Nov/2020 08:56:05] "GET /Report/ HTTP/1.1" 200 10857
[05/Nov/2020 08:56:06] "GET /patiantinfo/ HTTP/1.1" 200 10369
[05/Nov/2020 08:56:09] "GET /patiantinfo/new HTTP/1.1" 200 11731
[05/Nov/2020 08:56:14] "GET /patiantinfo/ HTTP/1.1" 200 10369
[05/Nov/2020 08:56:15] "GET /Report/ HTTP/1.1" 200 10857
[05/Nov/2020 08:58:05] "GET /WES/index/ HTTP/1.1" 200 11468
Internal Server Error: /WES//mnt/dfc_data1/project/lixuefei/WES/NGSWES0010001/Run/6.Final/QCStat.xls
Traceback (most recent call last):
  File "/mnt/dfc_data1/software/anaconda3/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/mnt/dfc_data1/software/anaconda3/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/mnt/dfc_data1/software/anaconda3/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/mnt/dfc_data1/home/lixuefei/Pipeline/Django/GeneticDisease/WES/views.py", line 177, in DownloadFile
    files = open(file_path, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/dfc_data1/project/lixuefei/WES/NGSWES0010001/Run/6.Final/QCStat.xls'
[05/Nov/2020 08:58:11] "GET /WES//mnt/dfc_data1/project/lixuefei/WES/NGSWES0010001/Run/6.Final/QCStat.xls HTTP/1.1" 500 70802
[05/Nov/2020 08:58:19] "GET /WES//mnt/dfc_data1/project/lixuefei/WES/NGSWES0010001/Run/6.Final/AllIntergrateMutation.xlsx HTTP/1.1" 200 29890147
[05/Nov/2020 09:05:33] "GET /patiantinfo/ HTTP/1.1" 200 10369
[05/Nov/2020 09:05:34] "GET /Sanger/index/ HTTP/1.1" 200 10796
[05/Nov/2020 09:05:39] "GET /WES/index/ HTTP/1.1" 200 11468
[05/Nov/2020 09:05:40] "GET /Report/ HTTP/1.1" 200 10857
[05/Nov/2020 09:05:42] "GET /Project/ HTTP/1.1" 200 6371
[05/Nov/2020 09:05:42] "GET /Report/ HTTP/1.1" 200 10857
[05/Nov/2020 09:05:48] "GET /WES/index/ HTTP/1.1" 200 11468
[05/Nov/2020 09:05:48] "GET /Sanger/index/ HTTP/1.1" 200 10796
[05/Nov/2020 09:05:49] "GET /patiantinfo/ HTTP/1.1" 200 10369
[05/Nov/2020 09:05:50] "GET /home/ HTTP/1.1" 200 8338
[05/Nov/2020 09:05:53] "GET /patiantinfo/ HTTP/1.1" 200 10369
[05/Nov/2020 09:05:54] "GET /Sanger/index/ HTTP/1.1" 200 10796
[05/Nov/2020 09:05:55] "GET /WES/index/ HTTP/1.1" 200 11468
[05/Nov/2020 09:05:57] "GET /Report/ HTTP/1.1" 200 10857
[05/Nov/2020 09:05:58] "GET /Sanger/index/ HTTP/1.1" 200 10796
[05/Nov/2020 09:06:08] "GET /patiantinfo/20B8199836/ HTTP/1.1" 200 13188
Internal Server Error: /patiantinfo/20B8199836/images/照片/2020-10-15/P1000122.JPG
Traceback (most recent call last):
  File "/mnt/dfc_data1/software/anaconda3/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/mnt/dfc_data1/software/anaconda3/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/mnt/dfc_data1/software/anaconda3/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/mnt/dfc_data1/home/lixuefei/Pipeline/Django/GeneticDisease/patiantinfo/views.py", line 159, in GetImage
    files = open(url_image, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'images/照片/2020-10-15/P1000122.JPG'
[05/Nov/2020 09:06:13] "GET /patiantinfo/20B8199836/images/%E7%85%A7%E7%89%87/2020-10-15/P1000122.JPG HTTP/1.1" 500 71866
Internal Server Error: /patiantinfo/20B8199836/images/病理/2020-10-15/P1000124.JPG
Traceback (most recent call last):
  File "/mnt/dfc_data1/software/anaconda3/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/mnt/dfc_data1/software/anaconda3/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/mnt/dfc_data1/software/anaconda3/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/mnt/dfc_data1/home/lixuefei/Pipeline/Django/GeneticDisease/patiantinfo/views.py", line 159, in GetImage
    files = open(url_image, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'images/病理/2020-10-15/P1000124.JPG'
[05/Nov/2020 09:06:24] "GET /patiantinfo/20B8199836/images/%E7%97%85%E7%90%86/2020-10-15/P1000124.JPG HTTP/1.1" 500 71866
Internal Server Error: /patiantinfo/20B8199836/images/送检单/2020-10-15/info_table.pdf
Traceback (most recent call last):
  File "/mnt/dfc_data1/software/anaconda3/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/mnt/dfc_data1/software/anaconda3/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/mnt/dfc_data1/software/anaconda3/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/mnt/dfc_data1/home/lixuefei/Pipeline/Django/GeneticDisease/patiantinfo/views.py", line 159, in GetImage
    files = open(url_image, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'images/送检单/2020-10-15/info_table.pdf'
[05/Nov/2020 09:06:28] "GET /patiantinfo/20B8199836/images/%E9%80%81%E6%A3%80%E5%8D%95/2020-10-15/info_table.pdf HTTP/1.1" 500 72002
[05/Nov/2020 09:07:59] "GET /patiantinfo/ HTTP/1.1" 200 10369
[05/Nov/2020 09:08:01] "GET /patiantinfo/20B8199836/ HTTP/1.1" 200 13188
Internal Server Error: /patiantinfo/20B8199836/images/照片/2020-10-15/P1000122.JPG
Traceback (most recent call last):
  File "/mnt/dfc_data1/software/anaconda3/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/mnt/dfc_data1/software/anaconda3/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/mnt/dfc_data1/software/anaconda3/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/mnt/dfc_data1/home/lixuefei/Pipeline/Django/GeneticDisease/patiantinfo/views.py", line 159, in GetImage
    files = open(url_image, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'images/照片/2020-10-15/P1000122.JPG'
[05/Nov/2020 09:08:03] "GET /patiantinfo/20B8199836/images/%E7%85%A7%E7%89%87/2020-10-15/P1000122.JPG HTTP/1.1" 500 71866
Internal Server Error: /patiantinfo/20B8199836/images/照片/2020-10-15/P1000122.JPG
Traceback (most recent call last):
  File "/mnt/dfc_data1/software/anaconda3/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/mnt/dfc_data1/software/anaconda3/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/mnt/dfc_data1/software/anaconda3/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/mnt/dfc_data1/home/lixuefei/Pipeline/Django/GeneticDisease/patiantinfo/views.py", line 159, in GetImage
    files = open(url_image, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'images/照片/2020-10-15/P1000122.JPG'
[05/Nov/2020 09:11:21] "GET /patiantinfo/20B8199836/images/%E7%85%A7%E7%89%87/2020-10-15/P1000122.JPG HTTP/1.1" 500 72001
[05/Nov/2020 09:11:23] "GET /patiantinfo/20B8199836/ HTTP/1.1" 200 13188
[05/Nov/2020 09:11:25] "GET /patiantinfo/20B8199836/ HTTP/1.1" 200 13188
Internal Server Error: /patiantinfo/20B8199836/images/照片/2020-10-15/P1000122.JPG
Traceback (most recent call last):
  File "/mnt/dfc_data1/software/anaconda3/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/mnt/dfc_data1/software/anaconda3/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/mnt/dfc_data1/software/anaconda3/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/mnt/dfc_data1/home/lixuefei/Pipeline/Django/GeneticDisease/patiantinfo/views.py", line 159, in GetImage
    files = open(url_image, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'images/照片/2020-10-15/P1000122.JPG'
[05/Nov/2020 09:11:26] "GET /patiantinfo/20B8199836/images/%E7%85%A7%E7%89%87/2020-10-15/P1000122.JPG HTTP/1.1" 500 71866
[05/Nov/2020 09:12:44] "GET /patiantinfo/20B8199836/ HTTP/1.1" 200 13188
[05/Nov/2020 09:12:45] "GET /patiantinfo/20B8199836/ HTTP/1.1" 200 13188
[05/Nov/2020 09:31:57] "GET /patiantinfo/ HTTP/1.1" 200 10369
[05/Nov/2020 09:31:59] "GET /patiantinfo/20B8199836/ HTTP/1.1" 200 13188
Internal Server Error: /patiantinfo/20B8199836/images/照片/2020-10-15/P1000122.JPG
Traceback (most recent call last):
  File "/mnt/dfc_data1/software/anaconda3/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/mnt/dfc_data1/software/anaconda3/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/mnt/dfc_data1/software/anaconda3/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/mnt/dfc_data1/home/lixuefei/Pipeline/Django/GeneticDisease/patiantinfo/views.py", line 159, in GetImage
    files = open(url_image, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'images/照片/2020-10-15/P1000122.JPG'
[05/Nov/2020 09:32:01] "GET /patiantinfo/20B8199836/images/%E7%85%A7%E7%89%87/2020-10-15/P1000122.JPG HTTP/1.1" 500 71866
Internal Server Error: /patiantinfo/20B8199836/images/照片/2020-10-15/P1000122.JPG
Traceback (most recent call last):
  File "/mnt/dfc_data1/software/anaconda3/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/mnt/dfc_data1/software/anaconda3/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/mnt/dfc_data1/software/anaconda3/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/mnt/dfc_data1/home/lixuefei/Pipeline/Django/GeneticDisease/patiantinfo/views.py", line 159, in GetImage
    files = open(url_image, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'images/照片/2020-10-15/P1000122.JPG'
[05/Nov/2020 09:32:50] "GET /patiantinfo/20B8199836/images/%E7%85%A7%E7%89%87/2020-10-15/P1000122.JPG HTTP/1.1" 500 71866
